### ISSUE TITLE
package hl7.au.base.template no longer on build server - needs ig.ini

### ISSUE THREAD

**Issue by robeastwood-agency** [hl7au/hl7.au.base.template#2]
See associated issue https://github.com/hl7au/hl7.au.fhir.template/issues/1

Builds of HL7AU FHIR IGs that point to the HL7AU template `hl7.au.fhir.template` fail due to this package no longer being present in the build server (ie https://build.fhir.org/ig/hl7au/).

This build failure occurs when building au-fhir-base or au-fhir-core **and** when the `hl7.au.fhir.template#current` package is not present in the local FHIR package cache. In this circumstance, the IG Publisher looks online for the package, as it is not found in the local cache. _Note that this occurs with building locally on a PC and the HL7 GitHub auto-builder._

See [this zulip thread in May 2022](https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Templates.20no.20longer.20triggering.20build) where it was identified that template repos in GitHub no longer auto-build without an ig.ini file. Subsequently, empty ig.ini files were added into these template repos so that the auto-builder succeeds - see this commit on the HL7 International base template https://github.com/HL7/ig-template-base/commit/e27d0bd17c0f09d34a611b206020dcbd43ee2a7f.

### Reproduce:
* delete (or rename) the `hl7.au.base.template#current` package in your FHIR package cache
* locally edit the ig.ini of either au-fhir-base or au-fhir-core FHIR IG, to point its template to `hl7.au.base.template#current` instead of `hl7.au.fhir.template#current`
* run IG publisher on either of au-fhir-base or au-fhir-core FHIR IG, in which the ig.ini was edited
* error is outputted to terminal with ` The package 'hl7.au.base.template' has no entry on the current build server `

### The fix
* add an empty ig.ini file at the root level of this repo

_Note_: this template is a dependency for the [fhir HL7AU template](https://github.com/hl7au/hl7.au.fhir.template) which suffers from the same issue. Therefore, a fix and rebuild of this template is required before the fix and rebuild occurs on the hl7.au.fhir.template.

**Comment by brettesler-ext** [comment]
[96bee9b5a48a6f5300ceedb56cfe6cf7fa5726fa ](https://github.com/hl7au/hl7.au.base.template/commit/96bee9b5a48a6f5300ceedb56cfe6cf7fa5726fa) added blank ini

**Comment by brettesler-ext** [comment]
+ https://github.com/hl7au/hl7.au.fhir.template/commit/37fc2e320cbb2513d2864e80bd4ad18fb11de84c for fhir template
